# Identificadores del proyecto en tu servidor SonarQube
sonar.projectKey=tw-app-com-labels
sonar.projectName=TW App Communication Labels and prompt command
sonar.projectVersion=1.0

# Ruta donde está tu código fuente de Python
sonar.sources=../tw-app-com-labels

# Evitamos que Sonar analice tus carpetas locales de logs y pruebas
sonar.exclusions=log/**, **/tests/**, *.json

# Codificación de los archivos
sonar.sourceEncoding=UTF-8
